#Configuration for Pinnit
#
# Author: Bharath Kumar

mongodb:
    uri: 'mongodb://localhost:27017/pinit'
AUTH:
    secret_key: 'AbC456'
    expiry: 600
AWS:
    access_key: 'AKIAJTTC27WJIKJ2ILBQ'
    secret_key: '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'
EMAIL:
    host : 'appgrid.qa.accedo.tv'
    port : '8085'
GENERAL:
    debug: 'false'