#Configuration for Pinnit
#
# Author: Bharath Kumar

version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  debug_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: logs/debug.log
    maxBytes: 10485760
    backupCount: 20
    encoding: utf8
  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: simple
    filename: logs/error.log
    maxBytes: 10485760
    backupCount: 20
    encoding: utf8
loggers:
  notewall:
    level: DEBUG
    handlers: [console,debug_file_handler,error_file_handler]
    propagate: no
root:
  level: DEBUG
  handlers: [console,debug_file_handler,error_file_handler]