# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Pinwall' do
pod 'Google/SignIn'
end

target 'PinwallTests' do

end

target 'PinwallUITests' do

end

